//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabsAdminASP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public int id_conf { get; set; }
        public string nombre_dominio { get; set; }
        public string ip_dominio { get; set; }
        public Nullable<int> usar_dominio { get; set; }
        public string usuario_admin { get; set; }
        public string pass_admin { get; set; }
        public Nullable<int> usar_usuario { get; set; }
        public string dominio { get; set; }
        public string ip_red { get; set; }
    }
}
